version: '3.8'

services:

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      target: build
    volumes:
      - ./src/app:/go/berbagi/src/app
    command: realize start --run --no-config
    ports:
      - 8000:8000
    env_file:
      - .env