version: '3.8'

services:

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      target: build
    volumes:
      - ./src/app:/go/berbagi/src/app
    command: realize start --run --no-config
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=

  redis:
    image: redis:latest
    ports:
      - 6379:6379
